/**
 * Where the generated files point.
 *
 * These live in one place because they end up committed into other people's
 * repositories, so getting one wrong is not something a later fix can take
 * back — and because the rename script rewrites the product name across the
 * source tree and needs a single spelling of it to find.
 */

export const PRODUCT = 'Redo';

/** The extension's own home. */
export const PRODUCT_URL = 'https://github.com/deepakvish001/Redo-By-Parikshaa-AI';

export const PARIKSHAA_URL = 'https://parikshaa.org';

/** A problem's page on Parikshaa, which shares LeetCode's slugs. */
export function parikshaaProblemUrl(slug: string): string {
  return `${PARIKSHAA_URL}/library/problems/${encodeURIComponent(slug)}`;
}

/**
 * The one line that closes every generated file.
 *
 * Deliberately a single `<sub>` line rather than a banner: these files sit in
 * the user's own repository, and anything larger is something they would strip
 * out — which would take the attribution with it.
 *
 * `Generated by Redo` must survive verbatim; `INDEX_MARKERS` in the sync uses
 * it to recognise an index this extension wrote, so an existing README is
 * never overwritten and one of ours is never abandoned.
 */
export function footer(verb: 'Generated' | 'Committed' = 'Generated'): string {
  return (
    `<sub>${verb} by [${PRODUCT}](${PRODUCT_URL}) — spaced-repetition revision for DSA, ` +
    `synced with [Parikshaa](${PARIKSHAA_URL}).</sub>`
  );
}

/**
 * Strings that identify an index this extension wrote.
 *
 * The sync only claims a repository's `README.md` when the file is absent or
 * already ours, so this list decides whether an existing index is adopted or
 * abandoned in favour of `SOLUTIONS.md`. Every wording the footer has ever had
 * has to stay here:
 *
 *  - `Generated by Redo` — plain text, before the footer carried links.
 *  - `Generated by [Redo]` — the current markdown-link form.
 *  - `Generated by DSA Revision Buddy` / `Smriti` — the earlier product names.
 *
 * Dropping one of these does not fail loudly. It silently starts writing
 * `SOLUTIONS.md` next to a `README.md` the user believes is still being
 * updated, which is worse.
 */
export const INDEX_MARKERS = [
  `Generated by [${PRODUCT}]`,
  `Generated by ${PRODUCT}`,
  'Generated by Smriti',
  'Generated by DSA Revision Buddy',
];

/**
 * The GitHub OAuth App client id, for device-flow sign-in.
 *
 * Empty on purpose. An OAuth App is registered by whoever publishes a build —
 * it is not a secret, but it is an account-level thing that a fork or a local
 * install does not inherit. With this blank, the sign-in button is hidden and
 * Settings says why, rather than offering a button that can only ever fail with
 * GitHub's unreadable `unauthorized_client`.
 *
 * To enable it: register an OAuth App at github.com/settings/developers, tick
 * "Enable Device Flow", and paste its Client ID here. No client secret is
 * involved — the device flow does not use one, which is exactly why it is the
 * only OAuth flow an extension can run honestly.
 */
export const GITHUB_CLIENT_ID = '';
