import { normalizeProblemId, solutionPath } from './paths.ts';
import type { SolvedProblem } from './types.ts';

const PLATFORM_LABEL: Record<string, string> = {
  leetcode: 'LeetCode',
  codeforces: 'Codeforces',
};

function isoDate(timestamp: number): string {
  return new Date(timestamp).toISOString().slice(0, 10);
}

function escapeCell(text: string): string {
  return text.replace(/\|/g, '\\|');
}

/** The per-problem README committed next to the solution file. */
export function buildProblemReadme(problem: SolvedProblem): string {
  const lines = [
    `# ${normalizeProblemId(problem.problemId)}. ${problem.title}`,
    '',
    `**Platform:** ${PLATFORM_LABEL[problem.platform] ?? problem.platform}  `,
    `**Difficulty:** ${problem.difficulty === 'unknown' ? 'n/a' : problem.difficulty}  `,
    `**Link:** ${problem.url}  `,
    `**Solved:** ${isoDate(problem.solvedAt)}  `,
    `**Language:** ${problem.language}  `,
    `**Attempts before accepted:** ${problem.attempts}`,
  ];

  if (problem.tags.length > 0) {
    lines.push('', `**Tags:** ${problem.tags.map((tag) => `\`${tag}\``).join(', ')}`);
  }

  const judge = [problem.runtimeNote, problem.memoryNote].filter(Boolean);
  if (judge.length > 0) {
    lines.push('', `**Judge:** ${judge.join(' · ')}`);
  }

  if (problem.solveTimeMs) {
    lines.push('', `**Time to solve:** ${Math.max(1, Math.round(problem.solveTimeMs / 60_000))} min`);
  }

  // The user's own analysis, kept separate from the judge's measurements.
  const complexity = [
    problem.complexity?.time && `**Time:** ${problem.complexity.time}`,
    problem.complexity?.space && `**Space:** ${problem.complexity.space}`,
  ].filter(Boolean);
  if (complexity.length > 0) {
    lines.push('', '## Complexity', '', complexity.join('  \n'));
  }

  lines.push('', '## Approach', '', problem.note?.trim() || '_Add your notes here._', '');
  lines.push('---', '', '<sub>Committed by Redo.</sub>', '');

  return lines.join('\n');
}

/**
 * The repository index. Regenerated on every sync from local state, so it
 * always reflects the full solved list rather than appending blindly.
 */
export function buildIndexReadme(problems: SolvedProblem[], generatedAt: number): string {
  const synced = problems
    .filter((problem) => problem.github.path)
    .sort((a, b) => b.solvedAt - a.solvedAt);

  const byDifficulty = synced.reduce<Record<string, number>>((counts, problem) => {
    counts[problem.difficulty] = (counts[problem.difficulty] ?? 0) + 1;
    return counts;
  }, {});

  const summary = ['easy', 'medium', 'hard', 'unknown']
    .filter((key) => byDifficulty[key])
    .map((key) => `${byDifficulty[key]} ${key === 'unknown' ? 'unrated' : key}`)
    .join(' · ');

  const lines = [
    '# DSA Solutions',
    '',
    `${synced.length} solved${summary ? ` — ${summary}` : ''}. Last updated ${isoDate(generatedAt)}.`,
    '',
    '| # | Problem | Platform | Difficulty | Language | Solved |',
    '| --- | --- | --- | --- | --- | --- |',
  ];

  for (const problem of synced) {
    const path = problem.github.path ?? solutionPath(problem);
    lines.push(
      [
        '',
        normalizeProblemId(problem.problemId),
        `[${escapeCell(problem.title)}](${encodeURI(path)})`,
        PLATFORM_LABEL[problem.platform] ?? problem.platform,
        problem.difficulty === 'unknown' ? '—' : problem.difficulty,
        escapeCell(problem.language),
        isoDate(problem.solvedAt),
        '',
      ].join(' | ').trim(),
    );
  }

  lines.push('', '---', '', '<sub>Generated by Redo.</sub>', '');
  return lines.join('\n');
}
