import { readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs';
import { resolve, dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

/**
 * Renames the product in one pass.
 *
 * The name appears in the manifest, the package, both UI surfaces, the docs
 * and the marker written into synced repositories. Doing it by hand means
 * missing one, so this does all of them and keeps the previous marker
 * recognised — a repository synced under the old name must keep its README.
 *
 *   npm run rename -- Spiral
 */

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const next = process.argv[2];

if (!next || !/^[A-Za-z][A-Za-z0-9 ]{1,24}$/.test(next)) {
  console.error('Usage: npm run rename -- <NewName>');
  process.exit(1);
}

const manifestPath = resolve(root, 'src/manifest.json');
const manifest = JSON.parse(readFileSync(manifestPath, 'utf8'));
const current = manifest.short_name;

if (!current) {
  console.error('src/manifest.json has no short_name to rename from.');
  process.exit(1);
}
if (current === next) {
  console.log(`Already called ${current}.`);
  process.exit(0);
}

const slug = (value) => value.toLowerCase().replace(/\s+/g, '-');

const TARGETS = ['src', 'scripts', 'docs', 'tests'];
const FILES = ['README.md', 'PRIVACY.md', 'package.json'];
const EXTENSIONS = /\.(ts|tsx|mjs|json|html|css|md)$/;

function walk(dir) {
  return readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const path = join(dir, entry.name);
    if (entry.isDirectory()) return walk(path);
    return EXTENSIONS.test(entry.name) ? [path] : [];
  });
}

const files = [
  ...TARGETS.filter((dir) => {
    try {
      return statSync(resolve(root, dir)).isDirectory();
    } catch {
      return false;
    }
  }).flatMap((dir) => walk(resolve(root, dir))),
  ...FILES.map((file) => resolve(root, file)),
];

let changed = 0;
for (const file of files) {
  const before = readFileSync(file, 'utf8');
  const after = before
    .replaceAll(current, next)
    .replaceAll(slug(current), slug(next));
  if (after !== before) {
    writeFileSync(file, after);
    changed += 1;
  }
}

// A repository synced under the old name must still be recognised as ours.
const syncPath = resolve(root, 'src/background/sync.ts');
const sync = readFileSync(syncPath, 'utf8');
const marker = `'Generated by ${current}'`;
if (!sync.includes(marker) && !sync.includes(`'Generated by ${next}'`)) {
  console.warn('Could not find the index marker to preserve — check src/background/sync.ts.');
} else if (!sync.includes(marker)) {
  writeFileSync(
    syncPath,
    sync.replace(
      `const INDEX_MARKERS = [`,
      `const INDEX_MARKERS = [\n  'Generated by ${current}',`,
    ),
  );
}

console.log(`Renamed ${current} -> ${next} across ${changed} files.`);
console.log('Now run: npm run icons && npm run build');
